### ISSUE TITLE
Test for mc_invalid_rate fails

### ISSUE THREAD

**Issue by EppChops** [obennet/sed-backend#80]
**Describe the bug**
The test for multiprocessing with invalid order of rate fails sometimes (i.e succeeds in running simulation). 

**To Reproduce**
1. Run tests on backend
2. Some of the times it fails

**Expected behavior**
The test should always give an invalid order of rate and thus cause the simulation to fail. 

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Captured log:
_____________________ test_run_mc_sim_rate_invalid_order ______________________

client = <starlette.testclient.TestClient object at 0x7f81694[34](https://github.com/obennet/sed-backend/actions/runs/4501057694/jobs/7920980127#step:6:35)a60>
std_headers = {'Authorization': '***'}
std_user = UserPost(username='test_user_9nz8idguw', email='test_user_9nz8idguw@sed-mock-email.com', full_name=None, disabled=False, password='7r44lnsw472mzl2vjup8', scopes='user')

    def test_run_mc_sim_rate_invalid_order(client, std_headers, std_user):
        #Setup
      current_user = impl_users.impl_get_user_with_username(std_user.username)
    
      project, vcs, design_group, design, settings = sim_tu.setup_single_simulation(current_user.id)
      tu.edit_rate_order_formulas(project.id, vcs.id, design_group.id)
      settings.monte_carlo = False
    
      #Act
      res = client.post(f'/api/cvs/project/{project.id}/simulation/run-multiprocessing',
                        headers=std_headers,
                        json = {
                          "sim_settings": settings.dict(),
                          "vcs_ids": [vcs.id],
                          "design_ids": [design[0].id]
                        })
    
      #Assert
>     assert res.status_code == 400
E     assert 200 == 400
E      +  where 200 = <Response [200]>.status_code

tests/apps/cvs/simulation/test_sim_multiprocessing.py:233: AssertionError
----------------------------- Captured stdout call -----------------------------
Seed settings vcs rows ['Transition', 'Information management', 'Quality management', 'Risk management', 'mo7um2eqsov4ygf1bzn', 'Human resource management', 'Life-cycle model management', 'Project assessment and control', 'Infrastructure management', 'Project portfolio management']
New rows ['Transition', 'Information management', 'Quality management', 'Risk management', 'mo7um2eqsov4ygf1bzn', 'Human resource management', 'Life-cycle model management', 'Project assessment and control', 'Infrastructure management', 'Project portfolio management']
Common elements ['Transition', 'Information management', 'Quality management', 'Risk management', 'mo7um2eqsov4ygf1bzn', 'Human resource management', 'Life-cycle model management', 'Project assessment and control', 'Infrastructure management', 'Project portfolio management']
Row len 10

**Comment by obennet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix simulation test fail](https://trello.com/c/161ox4Op/71-fix-simulation-test-fail)
